name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: indigo-history-346510

jobs:
  build:
    runs-on: ubuntu-latest

    environment: googlecloud # environment in which secrets is placed

    steps:

      - uses: actions/checkout@v3

      - name: Check if variable variable works 
        run: echo '${{secrets.TEST}} ${{secrets.TEST}} ...'

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{env.PROJECT_ID}}
          service_account_key: ${{ secrets.KEY_JSON }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ILoveMkdev
          runtime: java11
          project_id: mkdevyoutube
          entry_point: functions.ILoveMkdev

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding ILoveMkdev --member="allUsers" --role="roles/cloudfunctions.invoker"
      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"
